spring:
  application:
    name: room-service-api

  # ── Base de datos R2DBC (reactivo) ──────────────────────────────────────────
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hotelguestdb
    username: postgres
    password: BD1234+pg*
    properties:
      schema: public
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  # ── SQL inicialización ─────────────────────────────────────────────────────
  sql:
    init:
      mode: never

# ── Puerto del servidor ──────────────────────────────────────────────────────
server:
  port: 8083

# ── Logs ─────────────────────────────────────────────────────────────────────
logging:
  level:
    com.hotel: DEBUG
    org.springframework.r2dbc: INFO
    org.springframework.r2dbc.core.DefaultDatabaseClient: OFF
    reactor.netty: WARN # ← evita que Netty logee las URLs completas
# ── JWT ─────────────────────────────────────────────────────────────────────
jwt:
  secret: qX8$Nf2!Kz7@Lp4#Rw9&Ty6*Vm3%Hs1^Dc5?Bj8+Ua2=Eg7!